services:
  mongodb:
    image: mongo:8.0
    container_name: bluesky_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - bluesky_mongodb_data:/data/db
    networks:
      - bluesky-network

  redpanda:
    image: redpandadata/redpanda:v24.2.11
    container_name: bluesky_redpanda
    environment:
      - REDPANDA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - REDPANDA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - REDPANDA_ADVERTISED_LISTENERS=PLAINTEXT://redpanda:9092
      - REDPANDA_LISTENER_SASL_MECHANISMS=GSSAPI
      - REDPANDA_KAFKA_API_LISTENER=PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    volumes:
      - bluesky_redpanda_data:/var/lib/redpanda/data
    networks:
      - bluesky-network

networks:
  bluesky-network:
    driver: bridge

volumes:
  bluesky_mongodb_data:
  bluesky_redpanda_data: